export const CUSTOM_IMAGE_SRC = "https://www.alcohol.com.tw/upload/catalog_m/ALL_catalog_21A29_t2pvytyv7q.png";
export const CUSTOM_IMAGE_SRC_2 = "https://cohoimports.com/cdn/shop/files/Orion_334ml.png";

export const TRIP_DATA = {
        meta: {
          title: "沖繩五天四夜跨年之旅",
          dates: "2025/12/30 (二) - 2026/01/03 (六)",
          travelers: 2,
          rate: 0.21,
        },
        flights: [
          {
            type: "去程",
            code: "IT230",
            date: "12/30",
            time: "06:35 - 08:55",
            seat: "5AB",
            from: "TPE",
            to: "OKA",
          },
          {
            type: "回程",
            code: "IT233",
            date: "01/03",
            time: "21:30 - 22:05",
            seat: "28AB",
            from: "OKA",
            to: "TPE",
          },
        ],
        hotels: [
          {
            date: "12/30 (二)",
            name: "HOTEL NAHA CITY",
            area: "那霸",
            price: 6881,
            currency: "JPY",
            note: "停車 ¥1000/日",
          },
          {
            date: "12/31 (三)",
            name: "HOTEL YUQUESTA AGARIMACHI",
            area: "那霸",
            price: 8100,
            currency: "JPY",
            note: "含早餐",
          },
          {
            date: "01/01 (四)",
            name: "超級飯店 (Super Hotel)",
            area: "名護",
            price: 5440,
            currency: "JPY",
            note: "提早到選枕頭 (預估價格)",
          },
          {
            date: "01/02 (五)",
            name: "那霸倫勃朗風格飯店",
            area: "那霸",
            price: 4710,
            currency: "JPY",
            note: "Rembrandt Style Naha",
          },
        ],
        itinerary: [
          {
            day: 1,
            date: "12/30 (二)",
            dateStr: "2025-12-30",
            events: [
              {
                time: "06:35",
                endTime: "08:55",
                title: "抵達那霸機場",
                type: "transport",
                location: "那霸機場",
                cost: 0,
                note: "航班 IT230",
              },
              {
                time: "09:30",
                endTime: "10:00",
                title: "租車取車",
                type: "transport",
                location: "Brother Rent-A-Car (ブラザーレンタカー)",
                mapLocation: "沖縄県那覇市田原3-1-8",
                cost: 25470,
                note: "預計1小時，含保險。費用：¥25,470 (現場付)",
                mapLink: "https://maps.app.goo.gl/zqpsHZkhGTZXQbEd7",
              },
              {
                time: "10:30",
                endTime: "11:30",
                title: "早午餐：客美多咖啡",
                type: "meal",
                location: "客美多咖啡 沖繩糸滿店",
                cost: 1000,
                note: "停留約1小時",
              },
              {
                time: "12:00",
                endTime: "15:30",
                title: "沖繩世界 - 玉泉洞",
                type: "activity",
                location: "沖繩世界 文化王國・玉泉洞",
                cost: 4000,
                note: "13:30 毒蛇秀，Klook買一送一，費用¥4,000",
              },
              {
                time: "15:40",
                endTime: "16:30",
                title: "奧武島觀光",
                type: "activity",
                location: "奧武島",
                cost: 500,
                note: "停留約1小時，吃炸物",
              },
              {
                time: "17:00",
                endTime: "18:00",
                title: "Ricoland Okinawa",
                type: "activity",
                location: "Ricoland Okinawa",
                mapLocation: "Ricoland Okinawa",
                cost: 0,
                note: "機車用品店，停留1小時",
              },
              {
                time: "18:00",
                endTime: "19:00",
                title: "飯店 Check-in",
                type: "transport",
                location: "HOTEL NAHA CITY",
                mapLocation: "1 Chome-4-5 Matsuo, Naha, Okinawa 900-0014日本",
                cost: 6881,
                note: "停車費用 ¥1000/日。備註：10F吸菸區",
              },
              {
                time: "18:40",
                endTime: "20:30",
                title: "晚餐：Buchi Kumojiten (烤肉)",
                type: "meal",
                location: "Yakiniku Buchi Kumoji (燒肉 Buchi 久茂地店)",
                mapLocation: "Yakiniku Buchi Kumoji",
                cost: 5000,
                note: "【已預訂】18:40。必點：生牛肉赤身、土鍋飯。(提醒：訂了兩家，需選一家)",
              },
            ],
          },
          {
            day: 2,
            date: "12/31 (三)",
            dateStr: "2025-12-31",
            events: [
              {
                time: "07:00",
                endTime: "07:30",
                title: "早餐：福助玉子燒 或 豬肉蛋飯糰",
                type: "meal",
                location: "牧志市場周邊",
                cost: 1000,
                note: "走路10分鐘。福助7:30開 / 飯糰7:00開",
              },
              {
                time: "09:00",
                endTime: "13:00",
                title: "Parco City 逛街",
                type: "activity",
                location: "浦添西海岸 PARCO CITY",
                cost: 5000,
                note: "停車免費。開車約20分鐘",
              },
              {
                time: "13:30",
                endTime: "14:30",
                title: "午餐：敘敘苑燒肉",
                type: "meal",
                location: "敘敘苑 沖繩浦添PARCO CITY店",
                cost: 3000,
                note: "【已預訂】預約 13:30",
              },
              {
                time: "15:00",
                endTime: "16:00",
                title: "漫畫倉庫 / 港川外人住宅",
                type: "activity",
                location: "港川外人住宅街",
                cost: 1500,
                note: "浦添區。開車約9分鐘",
              },
              {
                time: "18:30",
                endTime: "19:00",
                title: "飯店 Check-in",
                type: "transport",
                location: "HOTEL YUQUESTA AGARIMACHI",
                mapLocation: "7-22 Higashimachi, Naha, Okinawa 900-0034日本",
                cost: 0,
                note: "需找停車場，盡量早回",
              },
              {
                time: "20:00",
                endTime: "21:30",
                title: "晚餐：LITOR",
                type: "meal",
                location: "LITOR",
                cost: 2000,
                note: "【已預訂】預約 20:00。不能遲到！(遲到當天退費也扣錢)",
              },
              {
                time: "22:00",
                endTime: "00:30",
                title: "跨年活動：Churasun 6",
                type: "activity",
                location: "Churasun 6",
                mapLocation: "Churasun 6, Naha",
                cost: 9000,
                note: "【已預訂】預約 22:00 (22:30 開始)。費用¥9,000",
              },
            ],
          },
          {
            day: 3,
            date: "01/01 (四)",
            dateStr: "2026-01-01",
            events: [
              {
                time: "08:00",
                endTime: "08:30",
                title: "早餐：A&W 漢堡",
                type: "meal",
                location: "A&W 牧港店",
                cost: 1500,
                note: "元旦早餐",
              },
              {
                time: "09:00",
                endTime: "09:30",
                title: "萬座毛",
                type: "activity",
                location: "萬座毛",
                cost: 200,
                note: "可以不去，可能會很趕，不然要更早出門。費用¥200",
              },
              {
                time: "12:00",
                endTime: "12:30",
                title: "午餐：許田休息站 或 CAMEL SANDWICH",
                type: "meal",
                location: "許田休息站 / CAMEL SANDWICH",
                mapLocation: "CAMEL SANDWICH",
                cost: 1500,
                note: "隨意吃或吃三明治",
              },
              {
                time: "14:00",
                endTime: "17:00",
                title: "美麗海水族館",
                type: "activity",
                location: "沖繩美麗海水族館",
                cost: 4360,
                note: "【攻略】P7北停車場最近。13:20排隊餵海豚、14:00餵海龜、15:00鯨鯊餵食(黑潮之海)。費用¥4,360",
              },
              {
                time: "18:00",
                endTime: "18:30",
                title: "飯店 Check-in",
                type: "transport",
                location: "Super Hotel Nago",
                mapLocation: "Super Hotel Okinawa Nago",
                cost: 5440,
                note: "提早到選枕頭。超級飯店(名護)",
              },
              {
                time: "19:00",
                endTime: "21:00",
                title: "晚餐：百年古家 大家 (阿古豬)",
                type: "meal",
                location: "Ufuya (百年古家 大家)",
                mapLocation: "Ufuya, Nago",
                cost: 4880,
                note: "【已預訂】預約 19:30",
              },
            ],
          },
          {
            day: 4,
            date: "01/02 (五)",
            dateStr: "2026-01-02",
            events: [
              {
                time: "07:00",
                endTime: "09:30",
                title: "早餐：飯店早餐",
                type: "meal",
                location: "Super Hotel Nago",
                cost: 0,
                note: "",
              },
              {
                time: "09:00",
                endTime: "10:00",
                title: "古宇利海洋塔",
                type: "activity",
                location: "古宇利海洋塔",
                cost: 2000,
                note: "欣賞風景。費用¥2,000",
              },
              {
                time: "11:30",
                endTime: "12:00",
                title: "午餐：古宇利蝦蝦飯",
                type: "meal",
                location: "Kouri Shrimp",
                mapLocation: "Kouri Shrimp Wagon",
                cost: 2160,
                note: "附近還有 NoBi",
              },
              {
                time: "13:30",
                endTime: "14:30",
                title: "美國村",
                type: "activity",
                location: "美國村",
                mapLocation: "American Village Okinawa",
                cost: 1500,
                note: "逛街拍照",
              },
              {
                time: "15:00",
                endTime: "16:00",
                title: "永旺夢樂城 (Aeon Mall)",
                type: "activity",
                location: "AEON MALL Okinawa Rycom",
                cost: 5000,
                note: "大型購物中心",
              },
              {
                time: "19:00",
                endTime: "20:00",
                title: "晚餐：傑克牛排",
                type: "meal",
                location: "Jack's Steak House (傑克牛排 那霸店)",
                mapLocation: "Jack's Steak House Naha Okinawa",
                cost: 3000,
                note: "可以19:00先去吃，再 Check-in 走回去",
              },
              {
                time: "19:30",
                endTime: "21:00",
                title: "飯店 Check-in",
                type: "transport",
                location: "Rembrandt Style Naha",
                mapLocation: "Rembrandt Style Naha",
                cost: 4710,
                note: "那霸倫勃朗風格飯店",
              },
            ],
          },
          {
            day: 5,
            date: "01/03 (六)",
            dateStr: "2026-01-03",
            events: [
              {
                time: "07:00",
                endTime: "09:30",
                title: "早餐：飯店早餐",
                type: "meal",
                location: "Rembrandt Style Naha",
                cost: 0,
                note: "",
              },
              {
                time: "09:30",
                endTime: "10:00",
                title: "波上宮",
                type: "activity",
                location: "波上宮",
                cost: 0,
                note: "參拜拍照",
              },
              {
                time: "10:00",
                endTime: "11:00",
                title: "早午餐：幸福鬆餅",
                type: "meal",
                location: "A Happy Pancake Umikaji Terrace",
                cost: 2000,
                note: "路邊停車免費，需排隊",
              },
              {
                time: "12:00",
                endTime: "13:00",
                title: "購物：iias 沖繩豐崎",
                type: "activity",
                location: "iias Okinawa Toyosaki",
                cost: 5000,
                note: "最後採買",
              },
              {
                time: "16:30",
                endTime: "17:00",
                title: "購物：Workman",
                type: "activity",
                location: "Workman Plus",
                cost: 5000,
                note: "機能服飾",
              },
              {
                time: "17:00",
                endTime: "18:00",
                title: "還車/前往機場",
                type: "transport",
                location: "那霸機場",
                cost: 0,
                note: "需預留還車時間",
              },
              {
                time: "21:30",
                endTime: "22:05",
                title: "返程航班",
                type: "transport",
                location: "IT233",
                cost: 0,
                note: "21:30 起飛",
              },
            ],
          },
        ],
        budget: [
          { item: "機票", twd: 17902, note: "買 / 都付了" },
          { item: "12/30 國際通住宿", twd: 1380, note: "買 / ¥6,881 (賀)" },
          { item: "12/31 國際通住宿", twd: 1620, note: "買 / ¥8,100 (賀)" },
          { item: "1/1 名護住宿", twd: 2176, note: "買 / ¥10,552 (賀)" },
          { item: "1/2 國際通住宿", twd: 1884, note: "買 / ¥9,396 (賀)" },
          { item: "租車 5天四夜", twd: 5094, note: "預訂 / ¥25,470 (現場付)" },
          { item: "日本譯文駕駛", twd: 256, note: "買 / 都付了" },
          { item: "門票 美麗海洋館", twd: 874, note: "未買 / ¥4,360 (賀)" },
          {
            item: "門票 玉泉洞",
            twd: 375,
            note: "買 / ¥4,000 (Klook買一送一)",
          },
          { item: "門票 古宇利島", twd: 375, note: "買 / ¥2,000 (賀)" },
          { item: "門票 萬座毛", twd: 40, note: "未買 / ¥200 (現場付)" },
          {
            item: "門票 Churasun 6",
            twd: 1800,
            note: "預訂 / ¥9,000 (現場付)",
          },
          { item: "旅遊險", twd: 1390, note: "買 / 12/22付錢" },
          { item: "esim", twd: 320, note: "未買 / 一人300左右" },
          { item: "加油錢(含停車費)", twd: 2000, note: "預估 / ¥10,000" },
          { item: "機場來回車資", twd: 930, note: "預估 / 單程高鐵訂票了430" },
          { item: "飲食", twd: 8500, note: "預估" },
          { item: "疫苗", twd: 2000, note: "買" },
        ],
      };
